# Generated by Django 4.0.4 on 2022-06-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbrand',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='waterbrand',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
